version: "3.8"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - mynetwork
  categories:
    depends_on:
      - mysqldb
    build: ./ATM
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/account?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 7777:7777
    networks:
      - mynetwork